version: '3'

networks:
  rumServiceNetwork:
    driver: bridge

services:
  rum:
    container_name: rum
    networks:
      - rumServiceNetwork
    image: <private_docker_center>/docker/rum:3.1.1
    volumes:
      - /data0/rum:/run/data
    ports:
      - 6809:6809
      - 6810:6810
    tty: true
    command: ["-ap=1", "-cert=/run/data/cert.txt", 
                "-certCheckCron=@every 1m",
                "-clientPort=0.0.0.0:6809",
                "-handIn=1",
                "-httpServerHost=0.0.0.0:6810", "-motd=/run/data/motd.txt", 
                "-nodeInfo=RumService",
                "-nodeName=Rum 2022",
                "-wzpCheckCorn=@every 30s",
                "-wzpFileLocation=/run/data/wzp.txt", "-plugin=rum_plugin:6811"]
    depends_on:
      - rum_plugin

  rum_plugin:
    container_name: rum_plugin
    image: <private_docker_center>/rum_plugin:dev
    ports:
     - 6811:6811
    depends_on:
      - redis
    networks:
      - rumServiceNetwork

  redis:
    networks:
      - rumServiceNetwork
    container_name: redis
    image: redis:latest
    volumes:
      - /data0/redis/data/:/data/
      - /data0/redis/redis.conf:/etc/redis/redis.conf

  seagull:
    container_name: api
    networks:
      - rumServiceNetwork
    image: <private_docker_center>/docker/seagull:dev
    volumes:
      - /data0/seagull/:/run/data/
    ports:
      - 6901:8080
    depends_on:
      - redis
    command: ["/run/SeagullServer",
              "-listen=0.0.0.0:8080",
              "-pergola-service=http://pergola:6810/",
              "-data-dir=/run/data/","-redis=redis:6379"]
